/* tslint:disable */
/* eslint-disable */
/**
 * Argento Oficina Virtual
 * Api para Portal de Clientes Argento
 *
 * The version of the OpenAPI document: 0.10.2
 * Contact: info@mts.com.do
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AccountChangePasswordModel
 */
export interface AccountChangePasswordModel {
    /**
     * 
     * @type {string}
     * @memberof AccountChangePasswordModel
     */
    'newPassword'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccountChangePasswordModel
     */
    'currentPassword'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccountChangePasswordModel
     */
    'confirmNewPassword'?: string | null;
}

