/* tslint:disable */
/* eslint-disable */
/**
 * Argento Oficina Virtual
 * Api para Portal de Clientes Argento
 *
 * The version of the OpenAPI document: 0.10.2
 * Contact: info@mts.com.do
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const BusinessUserType = {
    Client: 'Client',
    Operator: 'Operator',
    Officer: 'Officer',
    Admin: 'Admin'
} as const;

export type BusinessUserType = typeof BusinessUserType[keyof typeof BusinessUserType];



