/* tslint:disable */
/* eslint-disable */
/**
 * Argento Oficina Virtual
 * Api para Portal de Clientes Argento
 *
 * The version of the OpenAPI document: 0.10.2
 * Contact: info@mts.com.do
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BusinessUserTypeSaveModel } from './business-user-type-save-model';

/**
 * 
 * @export
 * @interface BusinessUserCreationModel
 */
export interface BusinessUserCreationModel {
    /**
     * 
     * @type {BusinessUserTypeSaveModel}
     * @memberof BusinessUserCreationModel
     */
    'type'?: BusinessUserTypeSaveModel;
    /**
     * 
     * @type {number}
     * @memberof BusinessUserCreationModel
     */
    'responsibleBusinessUserId'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof BusinessUserCreationModel
     */
    'businessId'?: number;
    /**
     * 
     * @type {string}
     * @memberof BusinessUserCreationModel
     */
    'userId'?: string | null;
}

