/* tslint:disable */
/* eslint-disable */
/**
 * Argento Oficina Virtual
 * Api para Portal de Clientes Argento
 *
 * The version of the OpenAPI document: 0.10.2
 * Contact: info@mts.com.do
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ErrorResult } from './error-result';
// May contain unused imports in some cases
// @ts-ignore
import { ExceptionFriendlyModel } from './exception-friendly-model';
// May contain unused imports in some cases
// @ts-ignore
import { RouteDataModel } from './route-data-model';

/**
 * 
 * @export
 * @interface CustomExceptionModel
 */
export interface CustomExceptionModel {
    /**
     * 
     * @type {string}
     * @memberof CustomExceptionModel
     */
    'message'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomExceptionModel
     */
    'process'?: string | null;
    /**
     * 
     * @type {ExceptionFriendlyModel}
     * @memberof CustomExceptionModel
     */
    'exception'?: ExceptionFriendlyModel;
    /**
     * 
     * @type {RouteDataModel}
     * @memberof CustomExceptionModel
     */
    'routeData'?: RouteDataModel;
    /**
     * 
     * @type {ErrorResult}
     * @memberof CustomExceptionModel
     */
    'error'?: ErrorResult;
}

