/* tslint:disable */
/* eslint-disable */
/**
 * Argento Oficina Virtual
 * Api para Portal de Clientes Argento
 *
 * The version of the OpenAPI document: 0.10.2
 * Contact: info@mts.com.do
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ExceptionFriendlyModel
 */
export interface ExceptionFriendlyModel {
    /**
     * 
     * @type {string}
     * @memberof ExceptionFriendlyModel
     */
    'typeName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExceptionFriendlyModel
     */
    'errorMessage'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExceptionFriendlyModel
     */
    'stackTrace'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExceptionFriendlyModel
     */
    'detailErrorMessage'?: string | null;
    /**
     * 
     * @type {ExceptionFriendlyModel}
     * @memberof ExceptionFriendlyModel
     */
    'innerException'?: ExceptionFriendlyModel;
}

