/* tslint:disable */
/* eslint-disable */
/**
 * Argento Oficina Virtual
 * Api para Portal de Clientes Argento
 *
 * The version of the OpenAPI document: 0.10.2
 * Contact: info@mts.com.do
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const FileType = {
    None: 'None',
    CSV: 'CSV',
    JSON: 'JSON',
    Excel: 'Excel',
    Txt: 'Txt',
    ExcelSpreadSheets: 'ExcelSpreadSheets',
    Pdf: 'Pdf',
    Xml: 'Xml'
} as const;

export type FileType = typeof FileType[keyof typeof FileType];



