/* tslint:disable */
/* eslint-disable */
/**
 * Argento Oficina Virtual
 * Api para Portal de Clientes Argento
 *
 * The version of the OpenAPI document: 0.10.2
 * Contact: info@mts.com.do
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FileUploadModel
 */
export interface FileUploadModel {
    /**
     * 
     * @type {string}
     * @memberof FileUploadModel
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FileUploadModel
     */
    'content'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FileUploadModel
     */
    'contentType'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof FileUploadModel
     */
    'length'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof FileUploadModel
     */
    'fileName'?: string | null;
}

