/* tslint:disable */
/* eslint-disable */
/**
 * Argento Oficina Virtual
 * Api para Portal de Clientes Argento
 *
 * The version of the OpenAPI document: 0.10.2
 * Contact: info@mts.com.do
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { HttpStatusCode } from './http-status-code';

/**
 * 
 * @export
 * @interface HttpResponseModel
 */
export interface HttpResponseModel {
    /**
     * 
     * @type {string}
     * @memberof HttpResponseModel
     */
    'responseAt'?: string | null;
    /**
     * 
     * @type {HttpStatusCode}
     * @memberof HttpResponseModel
     */
    'statusCode'?: HttpStatusCode;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof HttpResponseModel
     */
    'responseHeaders'?: { [key: string]: Array<string>; } | null;
    /**
     * 
     * @type {string}
     * @memberof HttpResponseModel
     */
    'rawResponse'?: string | null;
}



