/* tslint:disable */
/* eslint-disable */
/**
 * Argento Oficina Virtual
 * Api para Portal de Clientes Argento
 *
 * The version of the OpenAPI document: 0.10.2
 * Contact: info@mts.com.do
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface JwtTokenResponseModel
 */
export interface JwtTokenResponseModel {
    /**
     * 
     * @type {string}
     * @memberof JwtTokenResponseModel
     */
    'authToken'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JwtTokenResponseModel
     */
    'refreshToken'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JwtTokenResponseModel
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof JwtTokenResponseModel
     */
    'expiresAt'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof JwtTokenResponseModel
     */
    'userTokenId'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof JwtTokenResponseModel
     */
    'regeneratedQty'?: number;
    /**
     * 
     * @type {number}
     * @memberof JwtTokenResponseModel
     */
    'maxRegenerationQty'?: number | null;
}

