/* tslint:disable */
/* eslint-disable */
/**
 * Argento Oficina Virtual
 * Api para Portal de Clientes Argento
 *
 * The version of the OpenAPI document: 0.10.2
 * Contact: info@mts.com.do
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { LocalOperationLogModelInput } from './local-operation-log-model-input';
// May contain unused imports in some cases
// @ts-ignore
import { LocalOperationLogModelResult } from './local-operation-log-model-result';
// May contain unused imports in some cases
// @ts-ignore
import { OperationLogStatus } from './operation-log-status';
// May contain unused imports in some cases
// @ts-ignore
import { OperationLogType } from './operation-log-type';

/**
 * 
 * @export
 * @interface LocalOperationLogModel
 */
export interface LocalOperationLogModel {
    /**
     * 
     * @type {number}
     * @memberof LocalOperationLogModel
     */
    'id'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof LocalOperationLogModel
     */
    'isNullable'?: boolean;
    /**
     * 
     * @type {OperationLogStatus}
     * @memberof LocalOperationLogModel
     */
    'status'?: OperationLogStatus;
    /**
     * 
     * @type {string}
     * @memberof LocalOperationLogModel
     */
    'createdBy'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocalOperationLogModel
     */
    'createdOnUtc'?: string;
    /**
     * 
     * @type {string}
     * @memberof LocalOperationLogModel
     */
    'identifier'?: string | null;
    /**
     * 
     * @type {OperationLogType}
     * @memberof LocalOperationLogModel
     */
    'type'?: OperationLogType;
    /**
     * 
     * @type {LocalOperationLogModelInput}
     * @memberof LocalOperationLogModel
     */
    'input'?: LocalOperationLogModelInput;
    /**
     * 
     * @type {LocalOperationLogModelResult}
     * @memberof LocalOperationLogModel
     */
    'result'?: LocalOperationLogModelResult;
    /**
     * 
     * @type {string}
     * @memberof LocalOperationLogModel
     */
    'userIdentifier'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof LocalOperationLogModel
     */
    'executionTimeInMilliseconds'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof LocalOperationLogModel
     */
    'typeDescription'?: string | null;
}



