/* tslint:disable */
/* eslint-disable */
/**
 * Argento Oficina Virtual
 * Api para Portal de Clientes Argento
 *
 * The version of the OpenAPI document: 0.10.2
 * Contact: info@mts.com.do
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { LocalErrorLogModel } from './local-error-log-model';

/**
 * 
 * @export
 * @interface LocalErrorLogModelPaged
 */
export interface LocalErrorLogModelPaged {
    /**
     * 
     * @type {number}
     * @memberof LocalErrorLogModelPaged
     */
    'totalItems'?: number;
    /**
     * 
     * @type {number}
     * @memberof LocalErrorLogModelPaged
     */
    'page'?: number;
    /**
     * 
     * @type {number}
     * @memberof LocalErrorLogModelPaged
     */
    'totalPages'?: number;
    /**
     * 
     * @type {Array<LocalErrorLogModel>}
     * @memberof LocalErrorLogModelPaged
     */
    'items'?: Array<LocalErrorLogModel> | null;
    /**
     * 
     * @type {number}
     * @memberof LocalErrorLogModelPaged
     */
    'itemsCount'?: number | null;
}

