/* tslint:disable */
/* eslint-disable */
/**
 * Argento Oficina Virtual
 * Api para Portal de Clientes Argento
 *
 * The version of the OpenAPI document: 0.10.2
 * Contact: info@mts.com.do
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { QuoteProductQuantityDistributionModel } from './quote-product-quantity-distribution-model';
// May contain unused imports in some cases
// @ts-ignore
import { ValueIdItemResponseModel } from './value-id-item-response-model';

/**
 * 
 * @export
 * @interface QuoteProductsBaseRequestModel
 */
export interface QuoteProductsBaseRequestModel {
    /**
     * 
     * @type {Array<ValueIdItemResponseModel>}
     * @memberof QuoteProductsBaseRequestModel
     */
    'products'?: Array<ValueIdItemResponseModel> | null;
    /**
     * 
     * @type {Array<ValueIdItemResponseModel>}
     * @memberof QuoteProductsBaseRequestModel
     */
    'extras'?: Array<ValueIdItemResponseModel> | null;
    /**
     * 
     * @type {Array<QuoteProductQuantityDistributionModel>}
     * @memberof QuoteProductsBaseRequestModel
     */
    'distributions'?: Array<QuoteProductQuantityDistributionModel> | null;
}

