/* tslint:disable */
/* eslint-disable */
/**
 * Argento Oficina Virtual
 * Api para Portal de Clientes Argento
 *
 * The version of the OpenAPI document: 0.10.2
 * Contact: info@mts.com.do
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ContactInfoModel } from './contact-info-model';
// May contain unused imports in some cases
// @ts-ignore
import { FileUploadModel } from './file-upload-model';
// May contain unused imports in some cases
// @ts-ignore
import { QuoteProductQuantityDistributionModel } from './quote-product-quantity-distribution-model';
// May contain unused imports in some cases
// @ts-ignore
import { QuoteProductsClientType } from './quote-products-client-type';
// May contain unused imports in some cases
// @ts-ignore
import { ServiceRequestClientIdentificationModel } from './service-request-client-identification-model';
// May contain unused imports in some cases
// @ts-ignore
import { ServiceRequestClientModel } from './service-request-client-model';
// May contain unused imports in some cases
// @ts-ignore
import { ValueIdItemResponseModel } from './value-id-item-response-model';

/**
 * 
 * @export
 * @interface QuoteProductsRequestModel
 */
export interface QuoteProductsRequestModel {
    /**
     * 
     * @type {ServiceRequestClientModel}
     * @memberof QuoteProductsRequestModel
     */
    'client'?: ServiceRequestClientModel;
    /**
     * 
     * @type {ServiceRequestClientIdentificationModel}
     * @memberof QuoteProductsRequestModel
     */
    'clientIdentification'?: ServiceRequestClientIdentificationModel;
    /**
     * 
     * @type {Array<ContactInfoModel>}
     * @memberof QuoteProductsRequestModel
     */
    'clientContactInfo'?: Array<ContactInfoModel> | null;
    /**
     * 
     * @type {number}
     * @memberof QuoteProductsRequestModel
     */
    'requestId'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof QuoteProductsRequestModel
     */
    'businessOwnerId'?: number | null;
    /**
     * 
     * @type {QuoteProductsClientType}
     * @memberof QuoteProductsRequestModel
     */
    'clientType'?: QuoteProductsClientType;
    /**
     * 
     * @type {Array<ValueIdItemResponseModel>}
     * @memberof QuoteProductsRequestModel
     */
    'products'?: Array<ValueIdItemResponseModel> | null;
    /**
     * 
     * @type {Array<ValueIdItemResponseModel>}
     * @memberof QuoteProductsRequestModel
     */
    'extras'?: Array<ValueIdItemResponseModel> | null;
    /**
     * 
     * @type {Array<QuoteProductQuantityDistributionModel>}
     * @memberof QuoteProductsRequestModel
     */
    'distributions'?: Array<QuoteProductQuantityDistributionModel> | null;
    /**
     * 
     * @type {Array<FileUploadModel>}
     * @memberof QuoteProductsRequestModel
     */
    'files'?: Array<FileUploadModel> | null;
    /**
     * 
     * @type {boolean}
     * @memberof QuoteProductsRequestModel
     */
    'returnDataObject'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof QuoteProductsRequestModel
     */
    'sendEmail'?: boolean;
    /**
     * 
     * @type {any}
     * @memberof QuoteProductsRequestModel
     */
    'extraData'?: any | null;
    /**
     * 
     * @type {string}
     * @memberof QuoteProductsRequestModel
     */
    'responsibleUserId'?: string | null;
}



