/* tslint:disable */
/* eslint-disable */
/**
 * Argento Oficina Virtual
 * Api para Portal de Clientes Argento
 *
 * The version of the OpenAPI document: 0.10.2
 * Contact: info@mts.com.do
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RoleProfileBriefModel
 */
export interface RoleProfileBriefModel {
    /**
     * 
     * @type {number}
     * @memberof RoleProfileBriefModel
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof RoleProfileBriefModel
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RoleProfileBriefModel
     */
    'description'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof RoleProfileBriefModel
     */
    'businessId'?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof RoleProfileBriefModel
     */
    'isDefault'?: boolean;
}

