/* tslint:disable */
/* eslint-disable */
/**
 * Argento Oficina Virtual
 * Api para Portal de Clientes Argento
 *
 * The version of the OpenAPI document: 0.10.2
 * Contact: info@mts.com.do
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RouteDataModel
 */
export interface RouteDataModel {
    /**
     * 
     * @type {string}
     * @memberof RouteDataModel
     */
    'area'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RouteDataModel
     */
    'controller'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RouteDataModel
     */
    'action'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RouteDataModel
     */
    'module'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RouteDataModel
     */
    'location'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RouteDataModel
     */
    'scheme'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RouteDataModel
     */
    'host'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RouteDataModel
     */
    'path'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RouteDataModel
     */
    'url'?: string | null;
}

