/* tslint:disable */
/* eslint-disable */
/**
 * Argento Oficina Virtual
 * Api para Portal de Clientes Argento
 *
 * The version of the OpenAPI document: 0.10.2
 * Contact: info@mts.com.do
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ServiceRequestInteractionModelDataByType } from './service-request-interaction-model-data-by-type';
// May contain unused imports in some cases
// @ts-ignore
import { ServiceRequestInteractionType } from './service-request-interaction-type';
// May contain unused imports in some cases
// @ts-ignore
import { ServiceRequestModel } from './service-request-model';
// May contain unused imports in some cases
// @ts-ignore
import { Status } from './status';

/**
 * 
 * @export
 * @interface ServiceRequestInteractionModel
 */
export interface ServiceRequestInteractionModel {
    /**
     * 
     * @type {number}
     * @memberof ServiceRequestInteractionModel
     */
    'id'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ServiceRequestInteractionModel
     */
    'isNullable'?: boolean;
    /**
     * 
     * @type {Status}
     * @memberof ServiceRequestInteractionModel
     */
    'status'?: Status;
    /**
     * 
     * @type {string}
     * @memberof ServiceRequestInteractionModel
     */
    'createdBy'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ServiceRequestInteractionModel
     */
    'createdOnUtc'?: string;
    /**
     * 
     * @type {ServiceRequestInteractionType}
     * @memberof ServiceRequestInteractionModel
     */
    'type'?: ServiceRequestInteractionType;
    /**
     * 
     * @type {ServiceRequestInteractionModelDataByType}
     * @memberof ServiceRequestInteractionModel
     */
    'dataByType'?: ServiceRequestInteractionModelDataByType;
    /**
     * 
     * @type {string}
     * @memberof ServiceRequestInteractionModel
     */
    'concept'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ServiceRequestInteractionModel
     */
    'requestId'?: number;
    /**
     * 
     * @type {ServiceRequestModel}
     * @memberof ServiceRequestInteractionModel
     */
    'request'?: ServiceRequestModel;
    /**
     * 
     * @type {number}
     * @memberof ServiceRequestInteractionModel
     */
    'relatedToId'?: number | null;
    /**
     * 
     * @type {ServiceRequestInteractionModel}
     * @memberof ServiceRequestInteractionModel
     */
    'relatedTo'?: ServiceRequestInteractionModel;
}



