/* tslint:disable */
/* eslint-disable */
/**
 * Argento Oficina Virtual
 * Api para Portal de Clientes Argento
 *
 * The version of the OpenAPI document: 0.10.2
 * Contact: info@mts.com.do
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ServiceRequestClientModel
 */
export interface ServiceRequestClientModel {
    /**
     * 
     * @type {string}
     * @memberof ServiceRequestClientModel
     */
    'secondName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ServiceRequestClientModel
     */
    'secondLastName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ServiceRequestClientModel
     */
    'fullName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ServiceRequestClientModel
     */
    'firstName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ServiceRequestClientModel
     */
    'firstLastName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ServiceRequestClientModel
     */
    'birthDate'?: string | null;
}

