/* tslint:disable */
/* eslint-disable */
/**
 * Argento Oficina Virtual
 * Api para Portal de Clientes Argento
 *
 * The version of the OpenAPI document: 0.10.2
 * Contact: info@mts.com.do
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ServiceRequestEmailInteractionAttachmentInfoModel } from './service-request-email-interaction-attachment-info-model';
// May contain unused imports in some cases
// @ts-ignore
import { ServiceRequestEmailInteractionModel } from './service-request-email-interaction-model';
// May contain unused imports in some cases
// @ts-ignore
import { ServiceRequestEmailInteractionStatus } from './service-request-email-interaction-status';
// May contain unused imports in some cases
// @ts-ignore
import { ServiceRequestStatus } from './service-request-status';
// May contain unused imports in some cases
// @ts-ignore
import { ServiceRequestStatusChangeInteractionModel } from './service-request-status-change-interaction-model';

/**
 * @type ServiceRequestInteractionModelDataByType
 * @export
 */
export type ServiceRequestInteractionModelDataByType = ServiceRequestEmailInteractionModel | ServiceRequestStatusChangeInteractionModel | string;


