/* tslint:disable */
/* eslint-disable */
/**
 * Argento Oficina Virtual
 * Api para Portal de Clientes Argento
 *
 * The version of the OpenAPI document: 0.10.2
 * Contact: info@mts.com.do
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ServiceRequestEmailInteractionAttachmentInfoModel
 */
export interface ServiceRequestEmailInteractionAttachmentInfoModel {
    /**
     * 
     * @type {string}
     * @memberof ServiceRequestEmailInteractionAttachmentInfoModel
     */
    'filename'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ServiceRequestEmailInteractionAttachmentInfoModel
     */
    'contentLength'?: number;
    /**
     * 
     * @type {string}
     * @memberof ServiceRequestEmailInteractionAttachmentInfoModel
     */
    'contentId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ServiceRequestEmailInteractionAttachmentInfoModel
     */
    'contentType'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ServiceRequestEmailInteractionAttachmentInfoModel
     */
    'contentDisposition'?: string | null;
}

