/* tslint:disable */
/* eslint-disable */
/**
 * Argento Oficina Virtual
 * Api para Portal de Clientes Argento
 *
 * The version of the OpenAPI document: 0.10.2
 * Contact: info@mts.com.do
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AnonymousInfo } from './anonymous-info';
// May contain unused imports in some cases
// @ts-ignore
import { UserTokenLoginProviderSelector } from './user-token-login-provider-selector';

/**
 * 
 * @export
 * @interface UserTokenCreationModel
 */
export interface UserTokenCreationModel {
    /**
     * 
     * @type {string}
     * @memberof UserTokenCreationModel
     */
    'refreshToken'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserTokenCreationModel
     */
    'tokenIdentifier'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UserTokenCreationModel
     */
    'regenerateQty'?: number;
    /**
     * 
     * @type {AnonymousInfo}
     * @memberof UserTokenCreationModel
     */
    'generatedFrom'?: AnonymousInfo;
    /**
     * 
     * @type {string}
     * @memberof UserTokenCreationModel
     */
    'userId'?: string | null;
    /**
     * 
     * @type {UserTokenLoginProviderSelector}
     * @memberof UserTokenCreationModel
     */
    'loginProvider'?: UserTokenLoginProviderSelector;
    /**
     * 
     * @type {number}
     * @memberof UserTokenCreationModel
     */
    'maxRegenerationQty'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof UserTokenCreationModel
     */
    'expiresAt'?: string | null;
}



