/* tslint:disable */
/* eslint-disable */
/**
 * Argento Oficina Virtual
 * Api para Portal de Clientes Argento
 *
 * The version of the OpenAPI document: 0.10.2
 * Contact: info@mts.com.do
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AnonymousInfo } from './anonymous-info';
// May contain unused imports in some cases
// @ts-ignore
import { UserTokenStatus } from './user-token-status';

/**
 * 
 * @export
 * @interface UserTokenEditionModel
 */
export interface UserTokenEditionModel {
    /**
     * 
     * @type {string}
     * @memberof UserTokenEditionModel
     */
    'refreshToken'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserTokenEditionModel
     */
    'tokenIdentifier'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UserTokenEditionModel
     */
    'regenerateQty'?: number;
    /**
     * 
     * @type {AnonymousInfo}
     * @memberof UserTokenEditionModel
     */
    'generatedFrom'?: AnonymousInfo;
    /**
     * 
     * @type {number}
     * @memberof UserTokenEditionModel
     */
    'id'?: number;
    /**
     * 
     * @type {UserTokenStatus}
     * @memberof UserTokenEditionModel
     */
    'status'?: UserTokenStatus;
}



